// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUdJpVT1oweF9J9w-eue6M0rXPece9cpA',
    appId: '1:199711111558:web:9e8c03e25791ee147c5407',
    messagingSenderId: '199711111558',
    projectId: 'loginauth-77420',
    authDomain: 'loginauth-77420.firebaseapp.com',
    storageBucket: 'loginauth-77420.firebasestorage.app',
    measurementId: 'G-1F8PTLNMRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwAyTIi58jjyvrRRVd-T3fhlT0nYSCc3k',
    appId: '1:199711111558:android:173a1bae3738c8d47c5407',
    messagingSenderId: '199711111558',
    projectId: 'loginauth-77420',
    storageBucket: 'loginauth-77420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYkFusOdpMSNwM_XfkLLvWZrvJeWz3Ido',
    appId: '1:199711111558:ios:bf70e324a09263eb7c5407',
    messagingSenderId: '199711111558',
    projectId: 'loginauth-77420',
    storageBucket: 'loginauth-77420.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYkFusOdpMSNwM_XfkLLvWZrvJeWz3Ido',
    appId: '1:199711111558:ios:bf70e324a09263eb7c5407',
    messagingSenderId: '199711111558',
    projectId: 'loginauth-77420',
    storageBucket: 'loginauth-77420.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUdJpVT1oweF9J9w-eue6M0rXPece9cpA',
    appId: '1:199711111558:web:4c8ee157273d94547c5407',
    messagingSenderId: '199711111558',
    projectId: 'loginauth-77420',
    authDomain: 'loginauth-77420.firebaseapp.com',
    storageBucket: 'loginauth-77420.firebasestorage.app',
    measurementId: 'G-P1KR6D52FR',
  );
}
